# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-07 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.IntegerField()),
                ('img', models.CharField(max_length=100)),
                ('tite', models.CharField(max_length=256)),
                ('news', models.DecimalField(decimal_places=2, max_digits=7)),
                ('old', models.DecimalField(decimal_places=2, max_digits=7)),
                ('huy', models.CharField(max_length=100)),
                ('btn', models.CharField(max_length=50)),
            ],
        ),
    ]
