# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-07 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miya', '0002_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.CharField(max_length=100)),
                ('img2', models.CharField(max_length=100)),
                ('img3', models.CharField(max_length=100)),
                ('img4', models.CharField(max_length=100)),
                ('titt1', models.CharField(max_length=256)),
                ('titt2', models.CharField(max_length=256)),
                ('titt3', models.CharField(max_length=256)),
                ('newss1', models.DecimalField(decimal_places=2, max_digits=7)),
                ('newss2', models.DecimalField(decimal_places=2, max_digits=7)),
                ('newss3', models.DecimalField(decimal_places=2, max_digits=7)),
                ('old1', models.DecimalField(decimal_places=2, max_digits=7)),
                ('old2', models.DecimalField(decimal_places=2, max_digits=7)),
                ('old3', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
