# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-10 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miya', '0005_singlegoods2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
