# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-10 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miya', '0006_auto_20181210_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.CharField(default='title.ico', max_length=100),
        ),
    ]
