# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miya', '0007_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.IntegerField()),
                ('images', models.CharField(max_length=100)),
                ('tite', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('ptwo', models.CharField(max_length=256)),
                ('yahei', models.CharField(max_length=100)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.CharField(max_length=100)),
                ('reduction', models.CharField(max_length=50)),
                ('wushi', models.CharField(max_length=100)),
                ('select', models.CharField(max_length=50)),
                ('tittle', models.CharField(max_length=256)),
                ('imag', models.CharField(max_length=100)),
                ('numname', models.CharField(max_length=20)),
            ],
        ),
    ]
