# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miya', '0008_goodsdesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsdesc',
            old_name='select',
            new_name='selects',
        ),
        migrations.AlterField(
            model_name='goodsdesc',
            name='tite',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='goodsdesc',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
