# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miya', '0009_auto_20181211_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsdesc',
            name='tittle',
        ),
    ]
